# Generated by Django 4.2.3 on 2023-07-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usercomments_delete_commentsentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='origin_language',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='dictionary_word',
            field=models.CharField(max_length=100),
        ),
    ]
