# Generated by Django 4.2.3 on 2023-07-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_dictionaryentry_origin_language_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dictionaryentry',
            table='dictionary_entry',
        ),
        migrations.AlterModelTable(
            name='usercomments',
            table='user_comments',
        ),
    ]
